# Generated by Django 3.0 on 2020-03-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AppUser', verbose_name='sub')),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
    ]
